# Generated by Django 3.1.2 on 2020-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=200)),
                ('subreddit', models.CharField(default='None', max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('subreddits_moderated', models.CharField(default='None', max_length=200)),
                ('account_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
