# Generated by Django 3.1.2 on 2020-10-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default='None', max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
