# Generated by Django 3.1.2 on 2020-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_info', '0002_subreddit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subreddit',
        ),
    ]
