# Generated by Django 3.1.2 on 2020-10-29 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_info', '0003_delete_subreddit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mod',
            table='mod_data',
        ),
    ]
